## Interesting Pytorch functions !

**But what is pytorch?**


**Pytorch is an open-source, Python-based machine and deep learning framework, which is being widely used for several natural language processing and computer vision applications.**
**PyTorch was developed by Facebook’s AI Research and is adapted by several industries like Uber, Twitter, Salesforce, and NVIDIA.**

_Let's get started with some functions:_

- torch.tensor()
- torch.arange()
- torch.narrow()
- torch.rand()
- torch.randit()

**Also what is a Tensor?**

**A tensor is a number, vector, matrix or any n-dimensional array. Pytorch library is required for processing tensors.**

In [5]:
# to install pytorch

#!conda install pytorch cpuonly -c pytorch -y

In [2]:
import torch

## Function 1 ##

*Torch.tensor() always copies data.*

In [7]:
# Example 1 
torch.tensor([[4,5], [6,7.]])

tensor([[4., 5.],
        [6., 7.]])

In [8]:
# Example 1 - breaking point
torch.tensor([[1, 2], [3, 4.,7.]])

ValueError: expected sequence of length 2 at dim 1 (got 3)

The dimensions of the vector should be same.

## Function 2 ##

*Returns a 1-D tensor of size with values from the interval (start, end) taken with common difference.*

In [9]:
# Example 2 - working
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [14]:
# Example 2 (one more)
torch.arange(1, 5.5,1.5)

tensor([1.0000, 2.5000, 4.0000])

*Returns a 1-D tensor of values from start to end with step. Step is the gap between two values in the tensor.Here the step is 1.5.*

## Function 3 ##

*Returns a new tensor that is a narrowed version of input tensor. The dimension dim is input from start to start + length.*

In [7]:
# Example 3 - working
x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
torch.narrow(x, 0, 0, 2)



tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
torch.narrow(x, 1, 1, 2)

tensor([[2, 3],
        [5, 6],
        [8, 9]])

## Function 4 ##

*Returns a tensor filled with random numbers from a uniform distribution on the interval (0, 1)*.
*The shape of the tensor is defined by the variable argument size.*

In [3]:
# Example 4 - working
torch.rand(5)

tensor([0.9343, 0.4283, 0.3807, 0.6979, 0.5401])

In [4]:
# Example 4 - (one more)
torch.rand(3,3)

tensor([[0.3237, 0.1951, 0.8283],
        [0.4825, 0.4653, 0.4761],
        [0.6095, 0.1963, 0.4425]])

## Function 5 ##

*Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).*
*The shape of the tensor is defined by the variable argument size.*

In [5]:
# Example 5 - working
torch.randint(10, (2, 2))

tensor([[7, 9],
        [8, 4]])

In [6]:
# Example 5 - (one more)
torch.randint(10, (2, 2))

tensor([[1, 2],
        [4, 1]])

As you can see, the torch.randit() takes random values for defined low and high values and yes it's size too.

### Reference Links ###


Official documentation for torch.Tensor: https://pytorch.org/docs/stable/tensors.html